version: '3.8'
services:
  # 参考 https://amateur-engineer-blog.com/jenkins-docker
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:latest
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
